### ISSUE TITLE
notion-md/script.py does not target notion-md

### ISSUE THREAD

**Issue by bgoodwinbc** [Malsius/notion-ghpages#1]
Run notion-md/script.py --static /<repository_name>/static/images --content content/posts --url /images --db *** --key *** --hugo
  
Traceback (most recent call last):
  File "/home/runner/work/_<repository_name>_/_<repository_name>_/notion-md/script.py", line 181, in <module>
    pages = query_db(args.db)
  File "/home/runner/work/_<repository_name>/<repository_name>_/notion-md/script.py", line 128, in query_db
    for item in response["results"]:
KeyError: 'results'
Error: Process completed with exit code 1.

**Comment by Malsius** [comment]
Have you followed the [step-by-step guide](https://malsius.github.io/notion-ghpages/usage/) and copied [Notion DB template](https://malsius.notion.site/malsius/3602f007cbae4b76a4998a78caba0079?v=548ff3a915134267960b702e4b70047a) ?
